ALTER TABLE sync_jobs
  ADD COLUMN IF NOT EXISTS mode VARCHAR(16) NOT NULL DEFAULT 'incremental',
  ADD COLUMN IF NOT EXISTS started_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS finished_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS fetched_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS upserted_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS failed_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS error_code VARCHAR(64) NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS sync_checkpoints (
  id BIGSERIAL PRIMARY KEY,
  user_id VARCHAR(128) NOT NULL,
  source VARCHAR(32) NOT NULL,
  cursor TEXT NOT NULL DEFAULT '',
  last_synced_at_utc TIMESTAMPTZ NOT NULL DEFAULT '1970-01-01 00:00:00+00',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, source)
);

CREATE TABLE IF NOT EXISTS sync_errors (
  id BIGSERIAL PRIMARY KEY,
  job_id VARCHAR(128) NOT NULL,
  source VARCHAR(32) NOT NULL,
  source_activity_id VARCHAR(128) NOT NULL DEFAULT '',
  error_code VARCHAR(64) NOT NULL DEFAULT '',
  error_message TEXT NOT NULL DEFAULT '',
  retryable BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sync_errors_job ON sync_errors(job_id, created_at DESC);
