CREATE TABLE IF NOT EXISTS weather_forecasts (
  forecast_id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  forecast_date DATE NOT NULL,
  temp_max_c DOUBLE PRECISION,
  temp_min_c DOUBLE PRECISION,
  humidity DOUBLE PRECISION,
  precip_mm DOUBLE PRECISION,
  pressure_hpa DOUBLE PRECISION,
  visibility_km DOUBLE PRECISION,
  cloud_pct DOUBLE PRECISION,
  uv_index DOUBLE PRECISION,
  text_day TEXT,
  text_night TEXT,
  icon_day TEXT,
  icon_night TEXT,
  wind360_day INT,
  wind_dir_day TEXT,
  wind_scale_day TEXT,
  wind_speed_day_ms DOUBLE PRECISION,
  wind360_night INT,
  wind_dir_night TEXT,
  wind_scale_night TEXT,
  wind_speed_night_ms DOUBLE PRECISION,
  sunrise_time TIME,
  sunset_time TIME,
  moonrise_time TIME,
  moonset_time TIME,
  moon_phase TEXT,
  moon_phase_icon TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, forecast_date)
);

CREATE INDEX IF NOT EXISTS idx_weather_forecasts_user_date ON weather_forecasts(user_id, forecast_date);
